name: Scrape the page and notify to Slack if it was updated.

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '*/5 * * * *'

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Scrape the page
        id: scrape
        run: sh ./scrape.sh

      - name: Notify to Slack
        if: steps.scrape.outputs.changed == 'true'
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "<!test> \n ${{ steps.scrape.outputs.title }} \n <https://www.nike.com/jp/launch>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            
      - name: Push diff
        if: steps.scrape.outputs.changed == 'true'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add -u; \
            git commit -m "push differences by scheduler"; \
            git push origin main; \
          fi
