name: Scrape the page and notify to Slack if it was updated.

on:
  - workflow_dispatch
  ##  - schedule:
    ## - cron:  '* * 1 * *'  ## TODO: Set up this when this code is completed.

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Notify to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              “text”: “Hello“,
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}