name: Scrape the page and notify to Slack if it was updated.

on:
  - workflow_dispatch
  ##  - schedule:
    ## - cron:  '* * 1 * *'  ## TODO: Set up this when this code is completed.

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.scrape.outputs.changed }}

    steps:
      - uses: actions/checkout@v3

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Scrape the page
        id: scrape
        run: sh ./scrape.sh

      - name: Notify to Slack
        run: echo ${{steps.scrape.outputs.changed}}
      
      - name: Push diff
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add -u; \
            git commit -m "push differences by scheduler"; \
            git push origin main; \
          fi
